coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 50%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 50%
        threshold: 5%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "test/**/*"
  - "**/*_test.go"
